// Auth
export const FETCH_USER = 'FETCH_USER'

// Purchases
export const PURCHASE_LIST_REQUEST = 'PURCHASE_LIST_REQUEST'
export const PURCHASE_LIST_SUCCESS = 'PURCHASE_LIST_SUCCESS'
export const PURCHASE_LIST_FAIL = 'PURCHASE_LIST_FAIL'

export const PURCHASE_DETAILS_REQUEST = 'PURCHASE_DETAILS_REQUEST'
export const PURCHASE_DETAILS_SUCCESS = 'PURCHASE_DETAILS_SUCCESS'
export const PURCHASE_DETAILS_FAIL = 'PURCHASE_DETAILS_FAIL'
export const PURCHASE_DETAILS_RESET = 'PURCHASE_DETAILS_RESET'

export const PURCHASE_CREATE_REQUEST = 'PURCHASE_CREATE_REQUEST'
export const PURCHASE_CREATE_SUCCESS = 'PURCHASE_CREATE_SUCCESS'
export const PURCHASE_CREATE_FAIL = 'PURCHASE_CREATE_FAIL'
export const PURCHASE_CREATE_RESET = 'PURCHASE_CREATE_RESET'

export const PURCHASE_UPDATE_REQUEST = 'PURCHASE_UPDATE_REQUEST'
export const PURCHASE_UPDATE_SUCCESS = 'PURCHASE_UPDATE_SUCCESS'
export const PURCHASE_UPDATE_FAIL = 'PURCHASE_UPDATE_FAIL'
export const PURCHASE_UPDATE_RESET = 'PURCHASE_UPDATE_RESET'

export const PURCHASE_DELETE_REQUEST = 'PURCHASE_DELETE_REQUEST'
export const PURCHASE_DELETE_SUCCESS = 'PURCHASE_DELETE_SUCCESS'
export const PURCHASE_DELETE_FAIL = 'PURCHASE_DELETE_FAIL'
export const PURCHASE_DELETE_RESET = 'PURCHASE_DELETE_RESET'

// Purchase Categories
export const PURCHASE_CATEGORY_LIST_REQUEST = 'PURCHASE_CATEGORY_LIST_REQUEST'
export const PURCHASE_CATEGORY_LIST_SUCCESS = 'PURCHASE_CATEGORY_LIST_SUCCESS'
export const PURCHASE_CATEGORY_LIST_FAIL = 'PURCHASE_CATEGORY_LIST_FAIL'

export const PURCHASE_CATEGORY_CREATE_REQUEST =
  'PURCHASE_CATEGORY_CREATE_REQUEST'
export const PURCHASE_CATEGORY_CREATE_SUCCESS =
  'PURCHASE_CATEGORY_CREATE_SUCCESS'
export const PURCHASE_CATEGORY_CREATE_FAIL = 'PURCHASE_CATEGORY_CREATE_FAIL'
export const PURCHASE_CATEGORY_CREATE_RESET = 'PURCHASE_CATEGORY_CREATE_RESET'

export const PURCHASE_CATEGORY_DELETE_REQUEST =
  'PURCHASE_CATEGORY_DELETE_REQUEST'
export const PURCHASE_CATEGORY_DELETE_SUCCESS =
  'PURCHASE_CATEGORY_DELETE_SUCCESS'
export const PURCHASE_CATEGORY_DELETE_FAIL = 'PURCHASE_CATEGORY_DELETE_FAIL'
export const PURCHASE_CATEGORY_DELETE_RESET = 'PURCHASE_CATEGORY_DELETE_RESET'

// Accounts
export const ACCOUNT_LIST_REQUEST = 'ACCOUNT_LIST_REQUEST'
export const ACCOUNT_LIST_SUCCESS = 'ACCOUNT_LIST_SUCCESS'
export const ACCOUNT_LIST_FAIL = 'ACCOUNT_LIST_FAIL'

export const ACCOUNT_DETAILS_REQUEST = 'ACCOUNT_DETAILS_REQUEST'
export const ACCOUNT_DETAILS_SUCCESS = 'ACCOUNT_DETAILS_SUCCESS'
export const ACCOUNT_DETAILS_FAIL = 'ACCOUNT_DETAILS_FAIL'
export const ACCOUNT_DETAILS_RESET = 'ACCOUNT_DETAILS_RESET'

export const ACCOUNT_CREATE_REQUEST = 'ACCOUNT_CREATE_REQUEST'
export const ACCOUNT_CREATE_SUCCESS = 'ACCOUNT_CREATE_SUCCESS'
export const ACCOUNT_CREATE_FAIL = 'ACCOUNT_CREATE_FAIL'
export const ACCOUNT_CREATE_RESET = 'ACCOUNT_CREATE_RESET'

export const ACCOUNT_DELETE_REQUEST = 'ACCOUNT_DELETE_REQUEST'
export const ACCOUNT_DELETE_SUCCESS = 'ACCOUNT_DELETE_SUCCESS'
export const ACCOUNT_DELETE_FAIL = 'ACCOUNT_DELETE_FAIL'
export const ACCOUNT_DELETE_RESET = 'ACCOUNT_DELETE_RESET'

export const ACCOUNT_UPDATE_REQUEST = 'ACCOUNT_UPDATE_REQUEST'
export const ACCOUNT_UPDATE_SUCCESS = 'ACCOUNT_UPDATE_SUCCESS'
export const ACCOUNT_UPDATE_FAIL = 'ACCOUNT_UPDATE_FAIL'
export const ACCOUNT_UPDATE_RESET = 'ACCOUNT_UPDATE_RESET'
