// Auth
export const FETCH_USER = 'FETCH_USER'

// Purchases
export const PURCHASE_LIST_REQUEST = 'PURCHASE_LIST_REQUEST'
export const PURCHASE_LIST_SUCCESS = 'PURCHASE_LIST_SUCCESS'
export const PURCHASE_LIST_FAIL = 'PURCHASE_LIST_FAIL'

export const PURCHASE_CREATE_REQUEST = 'PURCHASE_CREATE_REQUEST'
export const PURCHASE_CREATE_SUCCESS = 'PURCHASE_CREATE_SUCCESS'
export const PURCHASE_CREATE_FAIL = 'PURCHASE_CREATE_FAIL'
export const PURCHASE_CREATE_RESET = 'PURCHASE_CREATE_RESET'

// Purchase Categories
export const PURCHASE_CATEGORY_LIST_REQUEST = 'PURCHASE_CATEGORY_LIST_REQUEST'
export const PURCHASE_CATEGORY_LIST_SUCCESS = 'PURCHASE_CATEGORY_LIST_SUCCESS'
export const PURCHASE_CATEGORY_LIST_FAIL = 'PURCHASE_CATEGORY_LIST_FAIL'

export const PURCHASE_CATEGORY_CREATE_REQUEST =
  'PURCHASE_CATEGORY_CREATE_REQUEST'
export const PURCHASE_CATEGORY_CREATE_SUCCESS =
  'PURCHASE_CATEGORY_CREATE_SUCCESS'
export const PURCHASE_CATEGORY_CREATE_FAIL = 'PURCHASE_CATEGORY_CREATE_FAIL'
export const PURCHASE_CATEGORY_CREATE_RESET = 'PURCHASE_CATEGORY_CREATE_RESET'

export const PURCHASE_CATEGORY_DELETE_REQUEST =
  'PURCHASE_CATEGORY_DELETE_REQUEST'
export const PURCHASE_CATEGORY_DELETE_SUCCESS =
  'PURCHASE_CATEGORY_DELETE_SUCCESS'
export const PURCHASE_CATEGORY_DELETE_FAIL = 'PURCHASE_CATEGORY_DELETE_FAIL'
export const PURCHASE_CATEGORY_DELETE_RESET = 'PURCHASE_CATEGORY_DELETE_RESET'
